name: Deploy to GitHub Pages

on:
  push:
    branches: [ master ]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '15'
    - run: npm ci
    - run: npm run build
    - uses: actions/upload-artifact@v2
      with:
        name: build
        path: build/
  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: gh-pages
          persist-credentials: false
          fetch-depth: 0
      - run: |
          git rm -rf .
          git clean -fdx
      - uses: actions/download-artifact@v2
        with:
          name: build
      - name: Display structure of downloaded files
        run: ls -R
      - run: git status
